import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

import '../app.dart';
import '../models/app_user.dart';
import '../models/consulta.dart';
import '../models/property_listing.dart';
import '../models/rental_payment.dart';
import '../services/auth_service.dart';
import '../services/mock_property_service.dart';
import '../services/mock_rental_service.dart';
import '../widgets/site_header.dart';

class CrmDashboardScreen extends StatefulWidget {
  const CrmDashboardScreen({super.key});
  @override State<CrmDashboardScreen> createState() => _CrmDashboardScreenState();
}

class _CrmDashboardScreenState extends State<CrmDashboardScreen> {
  final MockPropertyService _service = MockPropertyService.instance;
  final TextEditingController _search = TextEditingController();
  ConsultaEstado? _status; String? _location; String? _operation;

  void _go(BuildContext context, String route) => Navigator.pushNamed(context, route);
  Future<void> _open(String value) async => launchUrl(Uri.parse(value), mode: LaunchMode.platformDefault);
  @override void dispose() { _search.dispose(); super.dispose(); }

  @override
  Widget build(BuildContext context) => ValueListenableBuilder<AppUser?>(valueListenable: AuthService.instance.currentUser, builder: (context, user, _) {
    if (user?.canUseCrm != true) return _denied(context);
    final all = _service.fetchConsultas();
    final filtered = _service.buscarConsultas(query: _search.text, estado: _status, operacion: _operation, ubicacion: _location);
    final listings = _service.fetchAll(); final metrics = _service.fetchMetrics(); final rentals = MockRentalService.instance.fetchPayments();
    final active = all.where((c) => c.estado != ConsultaEstado.cerrado).length;
    final hot = all.where((c) => c.estado == ConsultaEstado.visitoPropiedad || c.estado == ConsultaEstado.reserva).length;
    final closed = all.where((c) => c.estado == ConsultaEstado.cerrado).length;
    final contacts = metrics.fold(0, (n, m) => n + m.contacts); final views = metrics.fold(0, (n, m) => n + m.views);
    final paid = rentals.where((r) => r.status == PaymentStatus.paid).length; final pending = rentals.where((r) => r.status == PaymentStatus.pending).length; final overdue = rentals.where((r) => r.status == PaymentStatus.overdue).length;

    return Scaffold(body: CustomScrollView(slivers: [
      SliverToBoxAdapter(child: SiteHeader(currentRoute: AppRoutes.crm, onGoHome: () => _go(context, AppRoutes.home), onGoSales: () => _go(context, AppRoutes.sales), onGoRentals: () => _go(context, AppRoutes.rentals), onGoContact: () => _go(context, AppRoutes.contact), onGoLogin: () => _go(context, AppRoutes.login), onGoProfile: () => _go(context, AppRoutes.profile), onGoCrm: () => _go(context, AppRoutes.crm))),
      SliverPadding(padding: const EdgeInsets.all(16), sliver: SliverToBoxAdapter(child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1240), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Panel comercial', style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 4), Text(user!.isOwner ? 'Administrá leads, alquileres, publicaciones y permisos.' : 'Gestioná tus oportunidades y el seguimiento comercial.')])) , const SizedBox(width: 12), Wrap(spacing: 8, children: [if (user.canCreateListings) OutlinedButton.icon(onPressed: () => _go(context, AppRoutes.createListing), icon: const Icon(Icons.add_business_outlined), label: const Text('Nueva publicación')), if (user.isOwner) OutlinedButton.icon(onPressed: () => _go(context, AppRoutes.admin), icon: const Icon(Icons.manage_accounts_outlined), label: const Text('Usuarios'))])]),
        const SizedBox(height: 20), _kpis(active, hot, closed, contacts, views), const SizedBox(height: 20), _filters(), const SizedBox(height: 20),
        Text('Pipeline de oportunidades · ${filtered.length}', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 10), _pipeline(filtered), const SizedBox(height: 24),
        _rentals(rentals, paid, pending, overdue), const SizedBox(height: 24), _performance(listings, metrics),
      ]))))),
    ]));
  });

  Widget _denied(BuildContext context) => Scaffold(body: Column(children: [SiteHeader(currentRoute: AppRoutes.crm, onGoHome: () => _go(context, AppRoutes.home), onGoSales: () => _go(context, AppRoutes.sales), onGoRentals: () => _go(context, AppRoutes.rentals), onGoContact: () => _go(context, AppRoutes.contact), onGoLogin: () => _go(context, AppRoutes.login), onGoProfile: () => _go(context, AppRoutes.profile), onGoCrm: () => _go(context, AppRoutes.crm)), const Expanded(child: Center(child: Text('No tenés permisos para utilizar el CRM.')))]));

  Widget _kpis(int active, int hot, int closed, int contacts, int views) { final data = [_KpiData(Icons.people_alt_outlined, 'Leads activos', '$active'), _KpiData(Icons.local_fire_department_outlined, 'Alta intención', '$hot'), _KpiData(Icons.check_circle_outline, 'Cerrados', '$closed'), _KpiData(Icons.touch_app_outlined, 'Contactos', '$contacts · $views vistas')]; return LayoutBuilder(builder: (context, c) => c.maxWidth < 720 ? Column(children: data.map((d) => Padding(padding: const EdgeInsets.only(bottom: 10), child: _Kpi(d))).toList()) : Row(children: data.map((d) => Expanded(child: Padding(padding: const EdgeInsets.only(right: 10), child: _Kpi(d)))).toList())); }

  Widget _filters() { final search = TextField(controller: _search, onChanged: (_) => setState(() {}), decoration: InputDecoration(labelText: 'Buscar nombre o teléfono', prefixIcon: const Icon(Icons.search_rounded), suffixIcon: _search.text.isEmpty ? null : IconButton(onPressed: () { _search.clear(); setState(() {}); }, icon: const Icon(Icons.close)))); final status = DropdownButtonFormField<ConsultaEstado?>(initialValue: _status, decoration: const InputDecoration(labelText: 'Estado'), items: [const DropdownMenuItem(value: null, child: Text('Todos')), ...ConsultaEstado.values.map((e) => DropdownMenuItem(value: e, child: Text(e.label)))], onChanged: (v) => setState(() => _status = v)); final operation = DropdownButtonFormField<String?>(initialValue: _operation, decoration: const InputDecoration(labelText: 'Operación'), items: [const DropdownMenuItem(value: null, child: Text('Todas')), ...MockPropertyService.operationTypes.map((e) => DropdownMenuItem(value: e, child: Text(e)))], onChanged: (v) => setState(() => _operation = v)); final location = DropdownButtonFormField<String?>(initialValue: _location, decoration: const InputDecoration(labelText: 'Ubicación'), items: [const DropdownMenuItem(value: null, child: Text('Todas')), ...MockPropertyService.locations.map((e) => DropdownMenuItem(value: e, child: Text(e)))], onChanged: (v) => setState(() => _location = v)); return Card(child: Padding(padding: const EdgeInsets.all(16), child: LayoutBuilder(builder: (context, c) => c.maxWidth < 800 ? Column(children: [search, const SizedBox(height: 10), status, const SizedBox(height: 10), operation, const SizedBox(height: 10), location]) : Row(children: [Expanded(flex: 2, child: search), const SizedBox(width: 10), Expanded(child: status), const SizedBox(width: 10), Expanded(child: operation), const SizedBox(width: 10), Expanded(child: location)])))); }

  Widget _pipeline(List<Consulta> consultas) => LayoutBuilder(builder: (context, c) { final columns = ConsultaEstado.values.map((state) => _PipelineColumn(state: state, items: consultas.where((x) => x.estado == state).toList(), onMove: (x, next) { _service.actualizarEstadoConsulta(consultaId: x.id, estado: next); setState(() {}); }, onAction: (x, action) { if (action == 'whatsapp') _open('https://wa.me/${x.whatsapp.replaceAll(RegExp(r'[^0-9]'), '')}'); if (action == 'phone') _open('tel:${x.telefono.replaceAll(' ', '')}'); if (action == 'email') _open('mailto:${x.email}'); })).toList(); return c.maxWidth < 900 ? Column(children: columns.map((w) => Padding(padding: const EdgeInsets.only(bottom: 10), child: w)).toList()) : Row(crossAxisAlignment: CrossAxisAlignment.start, children: columns.map((w) => Expanded(child: Padding(padding: const EdgeInsets.only(right: 10), child: w))).toList()); });

  Widget _rentals(List<RentalPayment> payments, int paid, int pending, int overdue) => Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Seguimiento de alquileres', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 4), const Text('Controlá quién pagó, quién adeuda y cuándo vence cada alquiler.')])) , Wrap(spacing: 8, children: [_MiniBadge(label: 'Pagados $paid', icon: Icons.check_circle_outline), _MiniBadge(label: 'Pendientes $pending', icon: Icons.schedule), _MiniBadge(label: 'Vencidos $overdue', icon: Icons.warning_amber_rounded)])]), const SizedBox(height: 14), LayoutBuilder(builder: (context, c) => c.maxWidth < 760 ? Column(children: payments.map(_rentalTile).toList()) : Column(children: payments.map((p) => _rentalRow(p)).toList()))]));
  Widget _rentalTile(RentalPayment p) => Card(color: const Color(0xFFF7F9FA), child: Padding(padding: const EdgeInsets.all(12), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_rentalMain(p), const SizedBox(height: 8), Text('Vence: ${_date(p.dueDate)}'), Text('Importe: ARS ${p.amountArs.toStringAsFixed(0)}'), if (p.paidDate != null) Text('Pagó: ${_date(p.paidDate!)}')] )));
  Widget _rentalRow(RentalPayment p) => Padding(padding: const EdgeInsets.symmetric(vertical: 5), child: Row(children: [Expanded(flex: 2, child: _rentalMain(p)), Expanded(child: Text(p.month)), Expanded(child: Text('Vence ${_date(p.dueDate)}')), Expanded(child: Text('ARS ${p.amountArs.toStringAsFixed(0)}')), _statusBadge(p.status)]));
  Widget _rentalMain(RentalPayment p) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(p.tenant, style: const TextStyle(fontWeight: FontWeight.w700)), Text(p.property)]);
  Widget _statusBadge(PaymentStatus s) { final label = s == PaymentStatus.paid ? 'PAGADO' : s == PaymentStatus.pending ? 'PENDIENTE' : 'VENCIDO'; final icon = s == PaymentStatus.paid ? Icons.check : s == PaymentStatus.pending ? Icons.schedule : Icons.warning_amber_rounded; return Chip(avatar: Icon(icon, size: 16), label: Text(label)); }
  String _date(DateTime d) => '${d.day.toString().padLeft(2, '0')}/${d.month.toString().padLeft(2, '0')}/${d.year}';

  Widget _performance(List<PropertyListing> listings, List<ListingMetrics> metrics) => Card(child: Padding(padding: const EdgeInsets.all(18), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Rendimiento de publicaciones', style: Theme.of(context).textTheme.titleLarge), const SizedBox(height: 5), const Text('Vistas y contactos generados por cada publicación.'), const SizedBox(height: 14), ...metrics.map((m) { final p = _service.findById(m.listingId); if (p == null) return const SizedBox.shrink(); return ListTile(contentPadding: EdgeInsets.zero, leading: const CircleAvatar(child: Icon(Icons.terrain_outlined)), title: Text(p.title), subtitle: Text(p.location), trailing: Text('${m.views} vistas\n${m.contacts} contactos', textAlign: TextAlign.right)); })])));
}

class _KpiData { const _KpiData(this.icon, this.label, this.value); final IconData icon; final String label; final String value; }
class _Kpi extends StatelessWidget { const _Kpi(this.data); final _KpiData data; @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(16), child: Row(children: [Container(width: 44, height: 44, decoration: BoxDecoration(color: const Color(0xFFEAF4F7), borderRadius: BorderRadius.circular(13)), child: Icon(data.icon, color: const Color(0xFF0A4D68))), const SizedBox(width: 12), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(data.label, style: const TextStyle(fontWeight: FontWeight.w600)), Text(data.value, style: Theme.of(context).textTheme.titleLarge)]))]))); }
class _MiniBadge extends StatelessWidget { const _MiniBadge({required this.label, required this.icon}); final String label; final IconData icon; @override Widget build(BuildContext context) => Chip(avatar: Icon(icon, size: 16), label: Text(label)); }
class _PipelineColumn extends StatelessWidget { const _PipelineColumn({required this.state, required this.items, required this.onMove, required this.onAction}); final ConsultaEstado state; final List<Consulta> items; final void Function(Consulta, ConsultaEstado) onMove; final void Function(Consulta, String) onAction; Color get color { switch (state) { case ConsultaEstado.nueva: return Colors.blue; case ConsultaEstado.seguimiento: return Colors.orange; case ConsultaEstado.visitoPropiedad: return Colors.deepPurple; case ConsultaEstado.reserva: return Colors.teal; case ConsultaEstado.cerrado: return Colors.green; } } @override Widget build(BuildContext context) => Card(child: Padding(padding: const EdgeInsets.all(12), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Container(width: 9, height: 9, decoration: BoxDecoration(color: color, shape: BoxShape.circle)), const SizedBox(width: 8), Expanded(child: Text(state.label, style: const TextStyle(fontWeight: FontWeight.w700))), Text('${items.length}', style: TextStyle(color: color, fontWeight: FontWeight.w800))]), const SizedBox(height: 10), if (items.isEmpty) const Padding(padding: EdgeInsets.all(14), child: Text('Sin oportunidades')) else ...items.take(6).map((x) => _LeadCard(x, color, onMove, onAction))]))); }
class _LeadCard extends StatelessWidget { const _LeadCard(this.item, this.color, this.onMove, this.onAction); final Consulta item; final Color color; final void Function(Consulta, ConsultaEstado) onMove; final void Function(Consulta, String) onAction; @override Widget build(BuildContext context) => Container(margin: const EdgeInsets.only(bottom: 8), padding: const EdgeInsets.all(11), decoration: BoxDecoration(color: const Color(0xFFF7F9FA), borderRadius: BorderRadius.circular(13)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Text(item.nombreCompleto, style: const TextStyle(fontWeight: FontWeight.w700))), PopupMenuButton<String>(padding: EdgeInsets.zero, icon: const Icon(Icons.more_horiz, size: 20), onSelected: (v) => onAction(item, v), itemBuilder: (_) => const [PopupMenuItem(value: 'whatsapp', child: Text('WhatsApp')), PopupMenuItem(value: 'phone', child: Text('Llamar')), PopupMenuItem(value: 'email', child: Text('Email'))])]), Text('${item.interes} · ${item.ubicacion}'), Text(item.presupuesto, style: TextStyle(color: color, fontWeight: FontWeight.w800)), const SizedBox(height: 6), DropdownButtonFormField<ConsultaEstado>(initialValue: item.estado, isDense: true, decoration: const InputDecoration(labelText: 'Estado'), items: ConsultaEstado.values.map((e) => DropdownMenuItem(value: e, child: Text(e.label))).toList(), onChanged: (v) { if (v != null) onMove(item, v); })])); }
