import 'package:flutter/material.dart';

import '../app.dart';
import '../models/property_listing.dart';
import '../services/mock_property_service.dart';
import '../services/property_image_catalog.dart';
import '../services/rating_service.dart';
import '../widgets/company_section.dart';
import '../widgets/site_footer.dart';
import '../widgets/site_header.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});
  @override State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  ListingType _operation = ListingType.sale;
  final TextEditingController _query = TextEditingController();
  @override void dispose() { _query.dispose(); super.dispose(); }
  void _go(BuildContext context, String route) { if (ModalRoute.of(context)?.settings.name == route) return; Navigator.pushNamed(context, route); }

  @override
  Widget build(BuildContext context) {
    final featured = MockPropertyService.instance.fetchByType(_operation).take(4).toList();
    return Scaffold(body: ListView(children: [
      SiteHeader(currentRoute: AppRoutes.home, onGoHome: () => _go(context, AppRoutes.home), onGoSales: () => _go(context, AppRoutes.sales), onGoRentals: () => _go(context, AppRoutes.rentals), onGoContact: () => _go(context, AppRoutes.contact), onGoLogin: () => _go(context, AppRoutes.login), onGoProfile: () => _go(context, AppRoutes.profile), onGoCrm: () => _go(context, AppRoutes.crm)),
      _hero(context), _trustStrip(context), _featured(context, featured), _mapSection(context), _metrics(context), _sellCta(context), _testimonials(context), const Padding(padding: EdgeInsets.symmetric(horizontal: 20), child: CompanySection()), const SizedBox(height: 24), const SiteFooter(),
    ]));
  }

  Widget _hero(BuildContext context) => Container(padding: const EdgeInsets.fromLTRB(20, 56, 20, 68), decoration: const BoxDecoration(gradient: LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [Color(0xFF061F2B), Color(0xFF0A4D68), Color(0xFF11627F)])), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: LayoutBuilder(builder: (context, c) { final compact = c.maxWidth < 850; return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Wrap(spacing: 8, runSpacing: 8, children: const [_HeroBadge(icon: Icons.verified_rounded, text: 'Propiedades seleccionadas'), _HeroBadge(icon: Icons.location_on_outlined, text: 'Posadas y Misiones')]), const SizedBox(height: 20), Text('Encontrá el lugar donde empieza tu próximo proyecto.', style: Theme.of(context).textTheme.displaySmall?.copyWith(color: Colors.white, fontSize: compact ? 36 : 52, height: 1.05)), const SizedBox(height: 14), const SizedBox(width: 760, child: Text('Venta, alquiler e inversiones inmobiliarias con una experiencia digital pensada para decidir mejor.', style: TextStyle(color: Colors.white70, fontSize: 18, height: 1.55))), const SizedBox(height: 28), _searchPanel(context), const SizedBox(height: 26), Wrap(spacing: 18, runSpacing: 10, children: const [_HeroTrust(icon: Icons.photo_camera_outlined, text: 'Presentación profesional'), _HeroTrust(icon: Icons.map_outlined, text: 'Búsqueda por ubicación'), _HeroTrust(icon: Icons.star_rounded, text: 'Opiniones de clientes')])]); })));

  Widget _searchPanel(BuildContext context) => Container(padding: const EdgeInsets.all(10), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(22), boxShadow: const [BoxShadow(blurRadius: 28, offset: Offset(0, 12), color: Colors.black26)]), child: LayoutBuilder(builder: (context, c) { final compact = c.maxWidth < 760; final search = Expanded(child: TextField(controller: _query, decoration: const InputDecoration(filled: false, prefixIcon: Icon(Icons.search_rounded), hintText: 'Buscá por ciudad, barrio o tipo de propiedad', border: InputBorder.none))); final operation = SegmentedButton<ListingType>(segments: const [ButtonSegment(value: ListingType.sale, label: Text('Venta'), icon: Icon(Icons.sell_outlined)), ButtonSegment(value: ListingType.rent, label: Text('Alquiler'), icon: Icon(Icons.key_outlined))], selected: {_operation}, onSelectionChanged: (v) => setState(() => _operation = v.first)); final action = FilledButton.icon(onPressed: () => _go(context, _operation == ListingType.sale ? AppRoutes.sales : AppRoutes.rentals), icon: const Icon(Icons.search_rounded), label: const Text('Buscar propiedades'), style: FilledButton.styleFrom(padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 16))); return compact ? Column(children: [operation, const SizedBox(height: 8), TextField(controller: _query, decoration: const InputDecoration(prefixIcon: Icon(Icons.search_rounded), hintText: 'Ciudad, barrio o propiedad')), const SizedBox(height: 8), SizedBox(width: double.infinity, child: action)]) : Row(children: [operation, const SizedBox(width: 8), search, const SizedBox(width: 8), action]); }));

  Widget _trustStrip(BuildContext context) => Padding(padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 22), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Wrap(alignment: WrapAlignment.spaceBetween, spacing: 26, runSpacing: 16, children: const [_TrustStat(value: '+120', label: 'propiedades publicadas'), _TrustStat(value: '24/7', label: 'consultas digitales'), _TrustStat(value: '4.8/5', label: 'experiencia valorada'), _TrustStat(value: '1', label: 'plataforma para operar')])));

  Widget _featured(BuildContext context, List<PropertyListing> listings) => Padding(padding: const EdgeInsets.fromLTRB(20, 34, 20, 20), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(_operation == ListingType.sale ? 'Propiedades destacadas en venta' : 'Propiedades destacadas en alquiler', style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 5), Text('Una selección para empezar a explorar.', style: Theme.of(context).textTheme.bodyLarge)])), OutlinedButton.icon(onPressed: () => _go(context, _operation == ListingType.sale ? AppRoutes.sales : AppRoutes.rentals), icon: const Icon(Icons.arrow_forward_rounded), label: const Text('Ver todas'))]), const SizedBox(height: 20), LayoutBuilder(builder: (context, c) { final columns = c.maxWidth > 980 ? 4 : c.maxWidth > 650 ? 2 : 1; return GridView.count(crossAxisCount: columns, shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), crossAxisSpacing: 16, mainAxisSpacing: 16, childAspectRatio: columns == 1 ? 1.3 : .78, children: listings.map((p) => _featuredCard(context, p)).toList()); })]))));

  Widget _featuredCard(BuildContext context, PropertyListing property) { final rating = RatingService.instance.average(property.id); final image = PropertyImageCatalog.forListing(property.id, property.images).first; return Card(clipBehavior: Clip.antiAlias, child: InkWell(onTap: () => Navigator.pushNamed(context, AppRoutes.detail, arguments: property), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Expanded(child: Stack(fit: StackFit.expand, children: [Image.network(image, fit: BoxFit.cover, cacheWidth: 800, cacheHeight: 600, filterQuality: FilterQuality.low, errorBuilder: (_, _, _) => ColoredBox(color: Theme.of(context).colorScheme.surfaceContainerHighest, child: const Icon(Icons.home_work_outlined, size: 42))), Positioned(left: 12, top: 12, child: _badge(context, property.type == ListingType.sale ? 'EN VENTA' : 'EN ALQUILER')), Positioned(right: 12, top: 12, child: Container(padding: const EdgeInsets.symmetric(horizontal: 9, vertical: 7), decoration: BoxDecoration(color: Colors.black54, borderRadius: BorderRadius.circular(20)), child: Row(children: [const Icon(Icons.star_rounded, color: Colors.amber, size: 16), const SizedBox(width: 3), Text(rating.toStringAsFixed(1), style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w800))]))) ])), Padding(padding: const EdgeInsets.all(15), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(property.title, maxLines: 1, overflow: TextOverflow.ellipsis, style: Theme.of(context).textTheme.titleMedium), const SizedBox(height: 4), Text(property.location, style: Theme.of(context).textTheme.bodyMedium), const SizedBox(height: 9), Row(children: [Expanded(child: Text('USD ${property.priceUsd.toStringAsFixed(0)}', style: Theme.of(context).textTheme.titleLarge?.copyWith(color: Theme.of(context).colorScheme.primary))), const Icon(Icons.arrow_outward_rounded, size: 18)])]))]))); }
  Widget _badge(BuildContext context, String text) => Container(padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 7), decoration: BoxDecoration(color: Theme.of(context).colorScheme.surface.withValues(alpha: .94), borderRadius: BorderRadius.circular(20)), child: Text(text, style: TextStyle(fontSize: 10, fontWeight: FontWeight.w900, color: Theme.of(context).colorScheme.primary)));

  Widget _mapSection(BuildContext context) => Padding(padding: const EdgeInsets.fromLTRB(20, 60, 20, 20), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Container(padding: const EdgeInsets.all(26), decoration: BoxDecoration(color: Theme.of(context).colorScheme.surfaceContainerHighest.withValues(alpha: .38), borderRadius: BorderRadius.circular(30), border: Border.all(color: Theme.of(context).dividerColor)), child: LayoutBuilder(builder: (context, c) { final compact = c.maxWidth < 800; final copy = Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(padding: const EdgeInsets.symmetric(horizontal: 11, vertical: 7), decoration: BoxDecoration(color: Theme.of(context).colorScheme.primaryContainer, borderRadius: BorderRadius.circular(20)), child: Text('EXPLORÁ POR UBICACIÓN', style: TextStyle(fontSize: 11, fontWeight: FontWeight.w900, color: Theme.of(context).colorScheme.primary))), const SizedBox(height: 14), Text('Encontrá propiedades donde realmente querés vivir.', style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 9), Text('Visualizá zonas, compará oportunidades y abrí la ubicación en Google Maps.', style: Theme.of(context).textTheme.bodyLarge), const SizedBox(height: 18), FilledButton.icon(onPressed: () => _go(context, AppRoutes.map), icon: const Icon(Icons.map_outlined), label: const Text('Explorar mapa'))]); final map = SizedBox(height: compact ? 260 : 330, child: const _HomeMapPreview()); return compact ? Column(crossAxisAlignment: CrossAxisAlignment.start, children: [copy, const SizedBox(height: 20), map]) : Row(children: [Expanded(child: copy), const SizedBox(width: 28), Expanded(child: map)]); }))));

  Widget _metrics(BuildContext context) => Container(margin: const EdgeInsets.only(top: 42), padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 54), color: Theme.of(context).colorScheme.primary, child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Una experiencia inmobiliaria pensada para convertir búsquedas en decisiones.', style: Theme.of(context).textTheme.headlineMedium?.copyWith(color: Colors.white)), const SizedBox(height: 28), LayoutBuilder(builder: (context, c) { final cols = c.maxWidth > 850 ? 4 : 2; return GridView.count(crossAxisCount: cols, shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), childAspectRatio: 2.2, children: const [_Metric(value: '96%', label: 'consultas atendidas'), _Metric(value: '4.8/5', label: 'satisfacción demo'), _Metric(value: '+35', label: 'zonas relevadas'), _Metric(value: '< 5 min', label: 'respuesta comercial objetivo')]); })])));

  Widget _sellCta(BuildContext context) => Padding(padding: const EdgeInsets.fromLTRB(20, 58, 20, 10), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Container(padding: const EdgeInsets.all(32), decoration: BoxDecoration(gradient: const LinearGradient(colors: [Color(0xFF102D3A), Color(0xFF173F50)]), borderRadius: BorderRadius.circular(30)), child: LayoutBuilder(builder: (context, c) { final compact = c.maxWidth < 720; final title = Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('¿Querés vender tu propiedad?', style: Theme.of(context).textTheme.headlineSmall?.copyWith(color: Colors.white)), const SizedBox(height: 7), const Text('Máxima exposición, fotografía, video y seguimiento comercial desde una sola plataforma.', style: TextStyle(color: Colors.white70, fontSize: 16, height: 1.45))]); final button = FilledButton.icon(onPressed: () => _go(context, AppRoutes.sellWithUs), icon: const Icon(Icons.campaign_outlined), label: const Text('Vendé con nosotros'), style: FilledButton.styleFrom(backgroundColor: Colors.white, foregroundColor: const Color(0xFF0A4D68), padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 15))); return compact ? Column(crossAxisAlignment: CrossAxisAlignment.start, children: [title, const SizedBox(height: 20), button]) : Row(children: [Expanded(child: title), const SizedBox(width: 24), button]); }))));

  Widget _testimonials(BuildContext context) => Padding(padding: const EdgeInsets.fromLTRB(20, 58, 20, 20), child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 1180), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Lo que valoran nuestros clientes', style: Theme.of(context).textTheme.headlineMedium), const SizedBox(height: 8), Text('La experiencia no termina cuando encontrás una propiedad.', style: Theme.of(context).textTheme.bodyLarge), const SizedBox(height: 22), LayoutBuilder(builder: (context, c) { final cols = c.maxWidth > 900 ? 3 : 1; const testimonials = [('Mariana B.', 'Compradora', 'La búsqueda por zona me permitió comparar varias opciones sin perder tiempo.'), ('Carlos F.', 'Inversor', 'La información de cada inmueble está presentada de forma muy clara y profesional.'), ('Lucía G.', 'Inquilina', 'Pude encontrar una propiedad, consultar y avanzar con el asesor desde el mismo lugar.')]; return GridView.count(crossAxisCount: cols, shrinkWrap: true, physics: const NeverScrollableScrollPhysics(), crossAxisSpacing: 16, mainAxisSpacing: 16, childAspectRatio: cols == 1 ? 2.4 : 1.35, children: testimonials.map((t) => Card(child: Padding(padding: const EdgeInsets.all(22), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Row(children: [Icon(Icons.star_rounded, color: Colors.amber), Icon(Icons.star_rounded, color: Colors.amber), Icon(Icons.star_rounded, color: Colors.amber), Icon(Icons.star_rounded, color: Colors.amber), Icon(Icons.star_rounded, color: Colors.amber)]), const SizedBox(height: 13), Expanded(child: Text('“${t.$3}”', style: Theme.of(context).textTheme.bodyLarge)), Text(t.$1, style: const TextStyle(fontWeight: FontWeight.w800)), const SizedBox(height: 3), Text(t.$2, style: Theme.of(context).textTheme.bodySmall)]))).toList()); })]))));
}

class _HeroBadge extends StatelessWidget { const _HeroBadge({required this.icon, required this.text}); final IconData icon; final String text; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.symmetric(horizontal: 11, vertical: 8), decoration: BoxDecoration(color: Colors.white.withValues(alpha: .1), borderRadius: BorderRadius.circular(30), border: Border.all(color: Colors.white24)), child: Row(mainAxisSize: MainAxisSize.min, children: [Icon(icon, color: Colors.white, size: 16), const SizedBox(width: 6), Text(text, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.w700, fontSize: 12))])); }
class _HeroTrust extends StatelessWidget { const _HeroTrust({required this.icon, required this.text}); final IconData icon; final String text; @override Widget build(BuildContext context) => Row(mainAxisSize: MainAxisSize.min, children: [Icon(icon, color: Colors.white70, size: 18), const SizedBox(width: 7), Text(text, style: const TextStyle(color: Colors.white70))]); }
class _TrustStat extends StatelessWidget { const _TrustStat({required this.value, required this.label}); final String value, label; @override Widget build(BuildContext context) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(value, style: Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight: FontWeight.w900)), Text(label, style: Theme.of(context).textTheme.bodySmall)]); }
class _Metric extends StatelessWidget { const _Metric({required this.value, required this.label}); final String value, label; @override Widget build(BuildContext context) => Padding(padding: const EdgeInsets.all(10), child: Column(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, children: [Text(value, style: const TextStyle(color: Colors.white, fontSize: 27, fontWeight: FontWeight.w900)), Text(label, style: const TextStyle(color: Colors.white70))])); }
class _HomeMapPreview extends StatelessWidget { const _HomeMapPreview(); @override Widget build(BuildContext context) => Card(clipBehavior: Clip.antiAlias, child: Stack(children: [Positioned.fill(child: CustomPaint(painter: _HomeMapPainter())), Positioned(top: 15, left: 15, child: Container(padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8), decoration: BoxDecoration(color: Colors.white, borderRadius: BorderRadius.circular(12), boxShadow: const [BoxShadow(blurRadius: 12, color: Colors.black12)]), child: const Row(children: [Icon(Icons.location_on_outlined, size: 17), SizedBox(width: 5), Text('Posadas · Misiones', style: TextStyle(fontWeight: FontWeight.w700))]))), ...[const _MapDot(x: .24, y: .36), const _MapDot(x: .51, y: .27), const _MapDot(x: .72, y: .44), const _MapDot(x: .39, y: .68), const _MapDot(x: .78, y: .72)]])); }
class _MapDot extends StatelessWidget { const _MapDot({required this.x, required this.y}); final double x, y; @override Widget build(BuildContext context) => Align(alignment: Alignment(x * 2 - 1, y * 2 - 1), child: Container(width: 34, height: 34, decoration: BoxDecoration(color: Theme.of(context).colorScheme.primary, shape: BoxShape.circle, border: Border.all(color: Colors.white, width: 4), boxShadow: const [BoxShadow(blurRadius: 10, color: Colors.black26)]), child: const Icon(Icons.home_work_rounded, color: Colors.white, size: 15))); }
class _HomeMapPainter extends CustomPainter { @override void paint(Canvas canvas, Size size) { canvas.drawRect(Offset.zero & size, Paint()..color = const Color(0xFFE7EFEA)); final road = Paint()..color = Colors.white..strokeWidth = 24..style = PaintingStyle.stroke; final fine = Paint()..color = const Color(0xFFD0DDD3)..strokeWidth = 1.5; for (var i = 1; i < 7; i++) canvas.drawLine(Offset(0, size.height * i / 7), Offset(size.width, size.height * (i + 1) / 8), road); for (var i = 1; i < 9; i++) canvas.drawLine(Offset(size.width * i / 9, 0), Offset(size.width * (i + 1) / 10, size.height), road); for (var i = 1; i < 10; i++) canvas.drawLine(Offset(0, size.height * i / 10), Offset(size.width, size.height * i / 10), fine); } @override bool shouldRepaint(covariant CustomPainter oldDelegate) => false; }
